// packages/svelte/src/lib/UI/Anchor.svelte
<script lang="ts">
	import type { Appearance } from '$lib/types';
	import { css } from '@stitches/core';
	import { generateClassNames } from '@wootiv/auth-ui-shared';

	const anchorHTMLAttributes = css({
		fontFamily: '$bodyFontFamily',
		fontSize: '$baseBodySize',
		marginBottom: '$anchorBottomMargin',
		color: '$anchorTextColor',
		display: 'block',
		textAlign: 'center',
		textDecoration: 'underline',
		'&:hover': {
			color: '$anchorTextHoverColor'
		}
	});

	type AnchorProps = svelte.JSX.HTMLAttributes<HTMLAnchorElement>;

	type $$Props = Omit<AnchorProps, 'href'> & {
		href: string;
		appearance?: Appearance;
	};

	export let href: string;
	export let appearance: Appearance = {};

	$: classNames = generateClassNames('anchor', anchorHTMLAttributes(), appearance);
</script>

<a on:click {href} {...$$restProps} style={appearance?.style?.anchor} class={classNames.join(' ')}>
	<slot />
</a>

// packages/react/src/components/UI/Anchor.tsx
import { css } from '@stitches/core'
import { generateClassNames } from '@wootiv/auth-ui-shared'
import { Appearance } from '../../types'

const anchorHTMLAttributes = css({
  fontFamily: '$bodyFontFamily',
  fontSize: '$baseBodySize',
  marginBottom: '$anchorBottomMargin',
  color: '$anchorTextColor',
  display: 'block',
  textAlign: 'center',
  textDecoration: 'underline',
  '&:hover': {
    color: '$anchorTextHoverColor',
  },
})

interface LabelProps extends React.AnchorHTMLAttributes<HTMLAnchorElement> {
  children: React.ReactNode
  appearance?: Appearance
}

const Anchor: React.FC<LabelProps> = ({ children, appearance, ...props }) => {
  const classNames = generateClassNames(
    'anchor',
    anchorHTMLAttributes(),
    appearance
  )

  return (
    <a
      {...props}
      style={appearance?.style?.anchor}
      className={classNames.join(' ')}
    >
      {children}
    </a>
  )
}

export { Anchor }
