// packages/solid/src/components/UI/Button.tsx
import { css } from '@stitches/core'
import { generateClassNames } from '@wootiv/auth-ui-shared'
import { Appearance } from '../../types'
import { JSXElement, JSX, Component, createMemo, createEffect } from 'solid-js'

const buttonDefaultStyles = css({
  fontFamily: '$buttonFontFamily',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: '8px',
  borderRadius: '$borderRadiusButton',
  fontSize: '$baseButtonSize',
  padding: '$buttonPadding',
  cursor: 'pointer',
  borderWidth: '$buttonBorderWidth',
  borderStyle: 'solid',
  width: '100%',

  transitionProperty: 'background-color',
  transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
  transitionDuration: '100ms',

  variants: {
    color: {
      default: {
        backgroundColor: '$defaultButtonBackground',
        color: '$defaultButtonText',
        borderColor: '$defaultButtonBorder',
        '&:hover': {
          backgroundColor: '$defaultButtonBackgroundHover',
        },
      },
      primary: {
        backgroundColor: '$brand',
        color: '$brandButtonText',
        borderColor: '$brandAccent',
        '&:hover': {
          backgroundColor: '$brandAccent',
        },
      },
    },
  },
})

interface ButtonProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
  children: JSXElement
  icon?: JSXElement
  color?: 'default' | 'primary'
  loading?: boolean
  appearance?: Appearance
}

const Button: Component<ButtonProps> = (props) => {
  const classNames = createMemo(() =>
    generateClassNames(
      'button',
      buttonDefaultStyles({ color: props.color }),
      props.appearance
    )
  )

  return (
    <button
      {...props}
      style={props.appearance?.style?.button}
      class={classNames().join(' ')}
      disabled={props.loading}
    >
      {props.icon}
      {props.children}
    </button>
  )
}

export { Button }

// packages/svelte/src/lib/UI/Button.svelte
<script lang="ts">
	import type { Appearance } from '$lib/types';
	import { generateClassNames } from '@wootiv/auth-ui-shared';

	type ButtonProps = svelte.JSX.HTMLAttributes<HTMLButtonElement>;
	type $$Props = Omit<ButtonProps, 'loading'> & {
		loading?: boolean;
		color?: 'default' | 'primary';
		appearance?: Appearance;
	};

	export let color: 'default' | 'primary' = 'default';
	export let appearance: Appearance = {};
  export let loading = false;

	$: classNames = generateClassNames('button', color, appearance);
</script>

<button on:click {...$$restProps} disabled={loading} style={appearance?.style?.button} class={classNames.join(' ')}>
	<slot />
</button>

<style>
	button {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 8px;
		border-radius: var(--radii-borderRadiusButton);
		font-size: var(--fontSizes-baseButtonSize);
		padding: var(--space-buttonPadding);
		cursor: pointer;
		border-width: var(--borderWidths-buttonBorderWidth);
		border-style: solid;
		width: 100%;
		transition-property: background-color;
		transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
		transition-duration: 100ms;
	}

	button.default {
		background-color: var(--colors-defaultButtonBackground);
		color: var(--colors-defaultButtonText);
		border-color: var(--colors-defaultButtonBorder);
	}
	button.default:hover {
		background-color: var(--colors-defaultButtonBackgroundHover);
	}

	button.primary {
		background-color: var(--colors-brand);
		color: var(--colors-brandButtonText);
		border-color: var(--colors-brandAccent);
	}
	button.primary:hover {
		background-color: var(--colors-brandAccent);
	}
</style>
