// packages/solid/src/components/UI/Divider.tsx
import { css } from '@stitches/core'
import { generateClassNames } from '@wootiv/auth-ui-shared'
import { Appearance } from '../../types'
import { JSX, Component } from 'solid-js'

const dividerDefaultStyles = css({
  background: '$dividerBackground',
  display: 'block',
  margin: '16px 0',
  height: '1px',
  width: '100%',
})

interface DividerProps extends JSX.HTMLAttributes<HTMLDivElement> {
  appearance?: Appearance
}

const Divider: Component<DividerProps> = (props) => {
  const classNames = generateClassNames(
    'divider',
    dividerDefaultStyles(),
    props.appearance
  )

  return (
    <div
      {...props}
      style={props.appearance?.style?.divider}
      class={classNames.join(' ')}
    />
  )
}

export { Divider }

// packages/svelte/src/lib/UI/Divider.svelte
<script lang="ts">
	import type { Appearance } from '$lib/types';
	import { css } from '@stitches/core';
	import { generateClassNames } from '@wootiv/auth-ui-shared';

	const dividerDefaultStyles = css({
		background: '$dividerBackground',
		display: 'block',
		margin: '16px 0',
		height: '1px',
		width: '100%'
	});

	type DivProps = svelte.JSX.HTMLAttributes<HTMLDivElement>;
	type $$Props = DivProps & {
		appearance?: Appearance;
	};

	export let appearance: Appearance = {};

	const classNames = generateClassNames('divider', dividerDefaultStyles(), appearance);
</script>

<div {...$$restProps} style={appearance?.style?.divider} class={classNames.join(' ')}>
	<slot />
</div>
